services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:4000'
    environment:
      - NODE_ENV=${NODE_ENV}
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '${WEB_PORT}:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
  pinecone:
    environment:
      PORT: 5080
      PINECONE_HOST: localhost
    ports:
      - '5080-5090:5080-5090'
    platform: linux/amd64
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
